### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by MalikZohaib** [akshay107/CNN-QA#2]
I am using following versions
Name: Theano
Version: 0.9

Name: gensim
Version: 2.3.0

Name: Keras
Version: 2.0.0

stack trace:
using Theano backend.
Traceback (most recent call last):
  File "tqa_system.py", line 62, in <module>
    tqa_sys.train_ndq_model()
  File "tqa_system.py", line 38, in train_ndq_model
    train_model = model.get_cnn_model2()
  File "/Users/muhammadzohaib/development/CNN-QA/TQA/code/model.py", line 152, in get_cnn_model2
    q_rep = tile_q(q_exp)
  File "/Users/muhammadzohaib/Library/Python/2.7/lib/python/site-packages/keras/engine/topology.py", line 545, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/muhammadzohaib/Library/Python/2.7/lib/python/site-packages/keras/layers/core.py", line 659, in call
    return self.function(inputs, **arguments)
  File "/Users/muhammadzohaib/development/CNN-QA/TQA/code/model.py", line 140, in <lambda>
    tile_q = Lambda(lambda xin: K.tile(xin,(1,self.max_opt_count,1,1)),output_shape=(self.max_opt_count,self.max_q_length,self.word_vec_size))
  File "/Users/muhammadzohaib/Library/Python/2.7/lib/python/site-packages/keras/backend/theano_backend.py", line 831, in tile
    y._keras_shape = tuple(xshape * n)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

**Comment by akshay107** [comment]
The error is due to the keras version. Kindly use Keras 2.0.8.

**Comment by MalikZohaib** [comment]
Thank you very much for quick help. If it will work with the PyLucene 7.7.1  ? or I must use 6.5.0.
